### ISSUE TITLE
Medium clue luck is being calculated with the hard clue completed kc

### ISSUE THREAD

**Issue by Chimerism** [peanubnutter/collection-log-luck#15]
I have 649 medium clues completed, but the plugin is calculating my percentiles in the medium clue log based off the number of hard clue kc I have (190), leading to incorrect values.

**Comment by peanubnutter** [comment]
What's your RSN? The collection log plugin (not my plugin) doesn't update KC until you get a new item or manually click upload, so maybe you just haven't uploaded your collection log in a while.

**Comment by peanubnutter** [comment]
Or do you have more information about which items look wrong?

The code looks fine. 
![Screenshot_20240812-102909~2](https://github.com/user-attachments/assets/0560a7db-8973-49be-9005-02db39167cd9)
![Screenshot_20240812-102804~2](https://github.com/user-attachments/assets/0e20ef74-0420-459a-aac1-3122020aeaba)

The plugin parses medium clue count, then ranger boots for example are a 1/1133 drop but you get 4 rolls on average.

**Comment by Chimerism** [comment]
Username is Chimerism. I haven’t done many mediums in a while so the log should be relatively up to date. I can see if the issue persists later today and upload a screenshot if needed.

**Comment by peanubnutter** [comment]
In the past few weeks I fixed a bug that made clue items seem much luckier than they actually were. But that was weeks ago so not sure whether or not that could be the issue.

**Comment by peanubnutter** [comment]
Thanks!
