### ISSUE TITLE
TOA Luck broken?

### ISSUE THREAD

**Issue by MrSaturnForensics** [peanubnutter/collection-log-luck#5]
% in toa don't work even if you input values?

**Comment by peanubnutter** [comment]
Works for me. Do you have any more information? Are other pages working?

![image](https://github.com/peanubnutter/collection-log-luck/assets/108562490/2f931c91-1d79-41cf-b50a-9683e753b229)

**Comment by MrSaturnForensics** [comment]
Sure, my log looks like this, all other logs work.
![image](https://github.com/peanubnutter/collection-log-luck/assets/86623595/cabc193a-2633-4ded-a0ec-ce6c4aeccb08)

My settings are as follows:
![image](https://github.com/peanubnutter/collection-log-luck/assets/86623595/170a0dbb-c8af-4412-8f60-822fbbb265fa)

Other collection log entries are working

**Comment by peanubnutter** [comment]
If all other logs work, then you probably just have to make sure that specific page is uploaded to collectionlog.net. Can you double check your username on that website and make sure you have that page uploaded?

**Comment by peanubnutter** [comment]
Oh, I just saw your settings. The unique chances are off by a factor of 100. It's a fraction, not percentage

**Comment by MrSaturnForensics** [comment]
Ah that makes sense, no worries! Might be worth clarifying that in the description when you hover it. as I defaulted to assuming it would be %

**Comment by peanubnutter** [comment]
Adding clarifications to the next update.
