### ISSUE TITLE
@esparano Dt2 awakener's orb not working

### ISSUE THREAD

**Issue by peanubnutter** [peanubnutter/collection-log-luck#6]
From @BrianBolti:        
              
              @esparano the collection-log-luck repo does not have issues enabled, took me a second to figure out how to reach out to you. Here's a bug that exists with the DT2 bosses :
![image](https://github.com/peanubnutter/collection-log-luck/assets/148491504/10bba13d-7a96-41ed-a0b6-a9c8e9b325b4)
![image](https://github.com/peanubnutter/collection-log-luck/assets/148491504/fa800b83-6397-44b3-8a91-d4015343e3be)

After referencing the data with collectionlog.net, it seems like awakener's orbs and chromium ingots aren't being tabulated correctly.

_Originally posted by @BrianBolti in https://github.com/peanubnutter/collection-log-luck/issues/4#issuecomment-1969614545_

**Comment by peanubnutter** [comment]
Hey @BrianBolti, I figured out what was causing this. You uploaded 2 of your DT2 boss pages to collectionlog.net, but not all of them. I guess on collectionlog.net, the number of awakener's orbs is stored separately per-boss, and can get out of sync, even though it's actually 1 value across all bosses in OSRS.

**Comment by BrianBolti** [comment]
@peanubnutter sick, nice catch! I'm not familiar w/ this code base so I can't really submit a PR for it, nor am I sure if I even have access to. Are we just notifying @esparano, or can you submit one?

**Comment by peanubnutter** [comment]
I'm signed in on a different account for some reason. Actually, I had considered closing this as a bug in the collection log plugin, but I think that a reasonable approach would be to take the highest value if an item is present on multiple pages but some pages are out of date.

**Comment by peanubnutter** [comment]
Just to be clear, the collection log plugin might accept a PR, but I tried in the past without success. It's also possible that limitations in the Runelite API could make a fix more difficult. Also, the collectionlog.net server side code is closed source, as far as I'm aware.

So, I think the easiest solution is just to take the highest item quantity on any page...

**Comment by peanubnutter** [comment]
I just realized that the solution I outlined above (taking the highest # of orbs on any page) will not work, because then, all other pages will be calculated incorrectly, but in the opposite direction (orb # is too high, but KC for bosses hasn't updated, so luck will be too high rather than too low for those bosses). I think the only solution is just to make sure that the collection log is up to date, and/or to update the collection log plugin itself (or server side logic).

**Comment by peanubnutter** [comment]
FYI this is actually completed in the upcoming release (though still could over-estimate luck if sharing out-of-date pages with multi-page drops using the !luck command). The calculations are usually correct on your client side now.
